// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/v1/pyproc.proto

package pyprocv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CallRequest represents a generic method call request
type CallRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique request ID for correlation
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Method name to invoke on the worker
	Method string `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	// JSON-encoded input data
	Input         []byte `protobuf:"bytes,3,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallRequest) Reset() {
	*x = CallRequest{}
	mi := &file_api_v1_pyproc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallRequest) ProtoMessage() {}

func (x *CallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_pyproc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallRequest.ProtoReflect.Descriptor instead.
func (*CallRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_pyproc_proto_rawDescGZIP(), []int{0}
}

func (x *CallRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CallRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *CallRequest) GetInput() []byte {
	if x != nil {
		return x.Input
	}
	return nil
}

// CallResponse represents a generic method call response
type CallResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Request ID for correlation
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Success status
	Ok bool `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	// JSON-encoded response body
	Body []byte `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	// Error message if ok is false
	ErrorMessage string `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// Error type for structured error handling
	ErrorType     string `protobuf:"bytes,5,opt,name=error_type,json=errorType,proto3" json:"error_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallResponse) Reset() {
	*x = CallResponse{}
	mi := &file_api_v1_pyproc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallResponse) ProtoMessage() {}

func (x *CallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_pyproc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallResponse.ProtoReflect.Descriptor instead.
func (*CallResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_pyproc_proto_rawDescGZIP(), []int{1}
}

func (x *CallResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CallResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *CallResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *CallResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *CallResponse) GetErrorType() string {
	if x != nil {
		return x.ErrorType
	}
	return ""
}

// HealthCheckRequest for worker health monitoring
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_api_v1_pyproc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_pyproc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_pyproc_proto_rawDescGZIP(), []int{2}
}

// HealthCheckResponse contains worker health information
type HealthCheckResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Overall health status
	Healthy bool `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	// Worker uptime in seconds
	UptimeSeconds int64 `protobuf:"varint,2,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	// Additional metadata about the worker
	Metadata      map[string]string `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_api_v1_pyproc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_pyproc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_pyproc_proto_rawDescGZIP(), []int{3}
}

func (x *HealthCheckResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthCheckResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *HealthCheckResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_api_v1_pyproc_proto protoreflect.FileDescriptor

const file_api_v1_pyproc_proto_rawDesc = "" +
	"\n" +
	"\x13api/v1/pyproc.proto\x12\tpyproc.v1\"K\n" +
	"\vCallRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x14\n" +
	"\x05input\x18\x03 \x01(\fR\x05input\"\x86\x01\n" +
	"\fCallResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\x12\x12\n" +
	"\x04body\x18\x03 \x01(\fR\x04body\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x12\x1d\n" +
	"\n" +
	"error_type\x18\x05 \x01(\tR\terrorType\"\x14\n" +
	"\x12HealthCheckRequest\"\xdd\x01\n" +
	"\x13HealthCheckResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12%\n" +
	"\x0euptime_seconds\x18\x02 \x01(\x03R\ruptimeSeconds\x12H\n" +
	"\bmetadata\x18\x03 \x03(\v2,.pyproc.v1.HealthCheckResponse.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\x96\x01\n" +
	"\rPyProcService\x127\n" +
	"\x04Call\x12\x16.pyproc.v1.CallRequest\x1a\x17.pyproc.v1.CallResponse\x12L\n" +
	"\vHealthCheck\x12\x1d.pyproc.v1.HealthCheckRequest\x1a\x1e.pyproc.v1.HealthCheckResponseB2Z0github.com/YuminosukeSato/pyproc/api/v1;pyprocv1b\x06proto3"

var (
	file_api_v1_pyproc_proto_rawDescOnce sync.Once
	file_api_v1_pyproc_proto_rawDescData []byte
)

func file_api_v1_pyproc_proto_rawDescGZIP() []byte {
	file_api_v1_pyproc_proto_rawDescOnce.Do(func() {
		file_api_v1_pyproc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_pyproc_proto_rawDesc), len(file_api_v1_pyproc_proto_rawDesc)))
	})
	return file_api_v1_pyproc_proto_rawDescData
}

var file_api_v1_pyproc_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_v1_pyproc_proto_goTypes = []any{
	(*CallRequest)(nil),         // 0: pyproc.v1.CallRequest
	(*CallResponse)(nil),        // 1: pyproc.v1.CallResponse
	(*HealthCheckRequest)(nil),  // 2: pyproc.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil), // 3: pyproc.v1.HealthCheckResponse
	nil,                         // 4: pyproc.v1.HealthCheckResponse.MetadataEntry
}
var file_api_v1_pyproc_proto_depIdxs = []int32{
	4, // 0: pyproc.v1.HealthCheckResponse.metadata:type_name -> pyproc.v1.HealthCheckResponse.MetadataEntry
	0, // 1: pyproc.v1.PyProcService.Call:input_type -> pyproc.v1.CallRequest
	2, // 2: pyproc.v1.PyProcService.HealthCheck:input_type -> pyproc.v1.HealthCheckRequest
	1, // 3: pyproc.v1.PyProcService.Call:output_type -> pyproc.v1.CallResponse
	3, // 4: pyproc.v1.PyProcService.HealthCheck:output_type -> pyproc.v1.HealthCheckResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_v1_pyproc_proto_init() }
func file_api_v1_pyproc_proto_init() {
	if File_api_v1_pyproc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_pyproc_proto_rawDesc), len(file_api_v1_pyproc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_pyproc_proto_goTypes,
		DependencyIndexes: file_api_v1_pyproc_proto_depIdxs,
		MessageInfos:      file_api_v1_pyproc_proto_msgTypes,
	}.Build()
	File_api_v1_pyproc_proto = out.File
	file_api_v1_pyproc_proto_goTypes = nil
	file_api_v1_pyproc_proto_depIdxs = nil
}
